### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by bhskr44** [gaurab6969/Login_Form_Page#1]
The HTML code you've written for the login page is clean and well-structured.

### **Suggestions for Improvement:**

1. **Action Handling**:
   - You may want to add an `action` attribute to the `<form>` tag to specify where the form data should be sent. This could be a backend script for validating login credentials.
   
   ```html
   <form class="login-form" action="login-handler" method="POST">
   ```

2. **Password Visibility**:
   - Consider adding an option for users to toggle the visibility of their password. A small “eye” icon or a checkbox can help users view their password if they want to check it.

   Example:
   ```html
   <input type="checkbox" id="show-password"> Show Password
   ```

4. **Mobile Responsiveness**:
   - To ensure the page looks good on all devices, you might consider adding some media queries to adjust padding, font sizes, and the container width for smaller screens.

   Example of a media query:
   ```css
   @media (max-width: 600px) {
       .container {
           padding: 15px;
           width: 90%;
       }

       .login-btn, .google-login {
           font-size: 14px;
       }
   }
   ```
